name: Auto IPTV Update

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch M3U
        run: |
          curl -L "https://latest.rkdyiptv.workers.dev/tg/rkdyiptv.m3u" -o playlist.m3u

      # 🇮🇳 INDIA FILTER
      - name: Filter India Channels
        run: |
          awk '
          BEGIN { keep=0 }
          /#EXTINF/ {
            if ($0 ~ /INDIA|STAR|SONY|ZEE|COLORS|SPORTS|HINDI|TATA|SUN|DD/) {
              keep=1
              print
              getline
              print
            } else {
              keep=0
            }
          }' playlist.m3u > india.m3u

      - name: Replace file
        run: mv india.m3u playlist.m3u

      - name: Commit & Push
        run: |
          git config --global user.name "iptv-bot"
          git config --global user.email "bot@iptv.com"
          git add playlist.m3u
          git commit -m "India IPTV update" || echo "No changes"
          git push
